doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '11.3'
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_id:
                class: App\Doctrine\Type\UserIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            SymfonyLiveWarsaw:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/App/Doctrine/mapping'
                prefix: 'SymfonyLiveWarsaw\Domain'
                alias: SymfonLiveWarsaw
